;[
  ts.createExpressionStatement(
    ts.createArrowFunction(
      undefined,
      undefined,
      [
        ts.createParameter(
          undefined,
          undefined,
          undefined,
          ts.createIdentifier('space'),
          undefined,
          ts.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
          undefined
        ),
        ts.createParameter(
          undefined,
          undefined,
          undefined,
          ts.createIdentifier('stream'),
          undefined,
          ts.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
          undefined
        ),
        ts.createParameter(
          undefined,
          undefined,
          undefined,
          ts.createIdentifier('value'),
          undefined,
          ts.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
          undefined
        )
      ],
      undefined,
      ts.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
      ts.createBlock(
        [
          ts.createExpressionStatement(
            ts.createBinary(
              ts.createElementAccess(
                ts.createPropertyAccess(
                  ts.createIdentifier('space'),
                  ts.createIdentifier('names')
                ),
                ts.createIdentifier('stream')
              ),
              ts.createToken(ts.SyntaxKind.FirstAssignment),
              ts.createTypeOf(ts.createIdentifier('value'))
            )
          )
        ],
        true
      )
    )
  )
]
